title = "Saddle Points"
blurb = "Detect saddle points in a matrix."
source = "J Dalbey's Programming Practice problems"
source_url = "https://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html"
