title = "Point Mutations"
blurb = "Calculate the Hamming difference between two DNA strands."
source = "The Calculating Point Mutations problem at Rosalind"
source_url = "https://rosalind.info/problems/hamm/"
