title = "Parallel Letter Frequency"
blurb = "Count the frequency of letters in texts using parallel computation."
deep_dive_youtube_id = "bkNQ1_kGHYE"
deep_dive_blurb = "We explore the differences between concurrency and parallelism, looking at different approaches taken by languages such as JavaScript, Go, Elixir and Rust."
