title = "Sieve"
blurb = "Use the Sieve of Eratosthenes to find all the primes from 2 up to a given number."
source = "Sieve of Eratosthenes at Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes"
