title = "Sieve"
blurb = "Use the Sieve of Eratosthenes to find all the primes from 2 up to a given number."
source = "Sieve of Eratosthenes at Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes"
deep_dive_youtube_id = "NXbCHabdv-s"
deep_dive_blurb = "We explore various approaches to the Sieve of Eratosthenes, starting with nested loops and lazy evaluation, then moving onto sets and finally looking at recursion."
