blurb = "Randomly generate Dungeons & Dragons characters."
source = "Simon Shine, Erik Schierboom"
source_url = "https://github.com/exercism/problem-specifications/issues/616#issuecomment-437358945"
title = "D&D Character"
deep_dive_youtube_id = "6fm44GiwEgM"
deep_dive_blurb = "We explore how to generate (seemingly) random dice rolls. You'll learn about seeds, pseudo random numbers and some common gotchas. Finally, we'll see how property-based testing is great for testing functions returning random values."
