title = "Zebra Puzzle"
blurb = "Solve the zebra puzzle."
source = "Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Zebra_Puzzle"
deep_dive_youtube_id = "waAFJKtsJrs"
deep_dive_blurb = "Explore 8 different ways of finding the Zebra Puzzle solution from 24 billion possible solutions, including ignoring invalid permutations as soon as possible, the AC-3 algorithm, a very succinct logic-based solution and even a genetic algorithm!"
