title = "Grains"
blurb = "Calculate the number of grains of wheat on a chessboard given that the number on each square doubles."
source = "The CodeRanch Cattle Drive, Assignment 6"
source_url = "https://coderanch.com/wiki/718824/Grains"
