title = "Affine Cipher"
blurb = "Create an implementation of the Affine cipher, an ancient encryption algorithm from the Middle East."
source = "Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Affine_cipher"
