language: node_js
node_js:
  - "6"

cache: yarn

script:
  - bin/check_required_files_present
  - sh bin/check_versions
  - bin/check_optional
  - bin/check_multi-line-string-array_contents
  - yarn test
