title = "Flower Field"
blurb = "Help avoid stepping on the flowers in a flower garden."
deep_dive_youtube_id = "dLT2h2hODhs"
deep_dive_blurb = "We explore nested for loops, clever use of min/max to simplify bounds checking, functional pipelines and using two-dimensional matrices."
