title = "Hello World"
blurb = "The classical introductory exercise. Just say \"Hello, World!\"."
source = "This is an exercise to introduce users to using Exercism"
source_url = "https://en.wikipedia.org/wiki/%22Hello,_world!%22_program"
