title = "Kindergarten Garden"
blurb = "Given a diagram, determine which plants each child in the kindergarten class is responsible for."
source = "Random musings during airplane trip."
source_url = "http://jumpstartlab.com"
