title = "Say"
blurb = "Given a number from 0 to 999,999,999,999, spell out that number in English."
source = "A variation on the JavaRanch CattleDrive, Assignment 4"
source_url = "https://coderanch.com/wiki/718804"
