title = "Phone Number"
blurb = "Clean up user-entered phone numbers so that they can be sent SMS messages."
source = "Exercise by the JumpstartLab team for students at The Turing School of Software and Design."
source_url = "https://turing.edu"
