title = "Pascal's Triangle"
blurb = "Compute Pascal's triangle up to a given number of rows."
source = "Pascal's Triangle at Wolfram Math World"
source_url = "https://www.wolframalpha.com/input/?i=Pascal%27s+triangle"
