title = "Prime Factors"
blurb = "Compute the prime factors of a given natural number."
source = "The Prime Factors Kata by Uncle Bob"
source_url = "https://web.archive.org/web/20221026171801/http://butunclebob.com/ArticleS.UncleBob.ThePrimeFactorsKata"
