title = "Pangram"
blurb = "Determine if a sentence is a pangram."
source = "Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Pangram"
deep_dive_youtube_id = "lFX12nbBrMU"
deep_dive_blurb = "We explore higher-order functions, set operations, using bitwise operations and more, looking at languages including Rust, Pharo, jq and Kotlin!"
