title = "Line up"
blurb = "Help lining up customers at Yaʻqūb's Deli."
source = "Based on previous work from Exercism contributors codedge and neenjaw"
source_url = "https://en.wikipedia.org/wiki/Ordinal_numeral"
