title = "Sum of Multiples"
blurb = "Given a number, find the sum of all the multiples of particular numbers up to but not including that number."
source = "A variation on Problem 1 at Project Euler"
source_url = "https://projecteuler.net/problem=1"
