title = "List Ops"
blurb = "Implement basic list operations."
deep_dive_youtube_id = "WMpPO4WnKxg"
deep_dive_blurb = "Enjoy a practical introduction to recursion, explore the imperative and functional alterantives to List Ops, and deep dive into tail-call recursion and accumulator functions."
