title = "Luhn"
blurb = "Given a number determine whether or not it is valid per the Luhn formula."
source = "The Luhn Algorithm on Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Luhn_algorithm"
deep_dive_youtube_id = "BId0VVDo7jA"
deep_dive_blurb = "We explore 8 different versions of Luhn, starting with a very tidy Ruby implementation, exploring some imperative and functional approaches, and ending up with a SQLite version that took Erik and Jeremy some work to decipher!"
