title = "Luhn"
blurb = "Given a number determine whether or not it is valid per the Luhn formula."
source = "The Luhn Algorithm on Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Luhn_algorithm"
