title = "Nucleotide Count"
blurb = "Given a DNA string, compute how many times each nucleotide occurs in the string."
source = "The Calculating DNA Nucleotides_problem at Rosalind"
source_url = "https://rosalind.info/problems/dna/"
