title = "Scrabble Score"
blurb = "Given a word, compute the Scrabble score for that word."
source = "Inspired by the Extreme Startup game"
source_url = "https://github.com/rchatley/extreme_startup"
deep_dive_youtube_id = "pFKLHOygtqQ"
deep_dive_blurb = "We explore pattern matching, higher-order functions, generator expressions, helper classes and more, looking at languages including F#, Ruby, Rust, AWK and Assembly!"
