title = "Trinary"
blurb = "Convert a trinary number, represented as a string (e.g. '102012'), to its decimal equivalent using first principles."
source = "All of Computer Science"
source_url = "https://www.wolframalpha.com/examples/mathematics/numbers/base-conversions"
