title = "Binary"
blurb = "Convert a binary number, represented as a string (e.g. '101010'), to its decimal equivalent using first principles."
source = "All of Computer Science"
source_url = "https://www.wolframalpha.com/examples/mathematics/numbers/base-conversions"
