title = "Circular Buffer"
blurb = "A data structure that uses a single, fixed-size buffer as if it were connected end-to-end."
source = "Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Circular_buffer"
deep_dive_youtube_id = "v1iU9QwpzQA"
deep_dive_blurb = "In this video we take a look at Circular Buffer, what they are, where they're used and different implementations - including queues, static and dynamic arrays, immutable data structures and a fun agent based implementation."
