title = "Circular Buffer"
blurb = "A data structure that uses a single, fixed-size buffer as if it were connected end-to-end."
source = "Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Circular_buffer"
