title = "Acronym"
blurb = "Convert a long phrase to its acronym."
source = "Julien Vanier"
source_url = "https://github.com/monkbroc"
deep_dive_youtube_id = "ofzqp4MFHvM"
deep_dive_blurb = "We take a gentle dive into regular expressions starting with basic whitespace matching, exploring unicode, and ending with negative lookbehinds. We finish off by looking at some other approaches to Acronym including state machines."
