title = "Variable Length Quantity"
blurb = "Implement variable length quantity encoding and decoding."
source = "A poor Splice developer having to implement MIDI encoding/decoding."
source_url = "https://splice.com"
