title = "Meetup"
blurb = "Calculate the date of meetups."
source = "Jeremy Hinegardner mentioned a Boulder meetup that happens on the Wednesteenth of every month"
source_url = "https://twitter.com/copiousfreetime"
