title = "Swift Scheduling"
blurb = "Convert delivery date descriptions to actual delivery dates."
source = "Erik Schierboom"
source_url = "https://github.com/exercism/problem-specifications/pull/2536"
