title = "RNA Transcription"
blurb = "Given a DNA strand, return its RNA complement."
source = "Hyperphysics"
source_url = "https://web.archive.org/web/20220408112140/http://hyperphysics.phy-astr.gsu.edu/hbase/Organic/transcription.html"
