title = "Simple Cipher"
blurb = "Implement a simple shift cipher like Caesar and a more secure substitution cipher."
source = "Substitution Cipher at Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Substitution_cipher"
