title = "Bob"
blurb = "Bob is a lackadaisical teenager. In conversation, his responses are very limited."
source = "Inspired by the 'Deaf Grandma' exercise in Chris Pine's Learn to Program tutorial."
source_url = "https://pine.fm/LearnToProgram/?Chapter=06"
