title = "Diffie-Hellman"
blurb = "Diffie-Hellman key exchange."
source = "Wikipedia, 1024 bit key from www.cryptopp.com/wiki."
source_url = "https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange"
