title = "Camicia"
blurb = "Simulate the card game and determine whether the match ends or enters an infinite loop."
source = "Beggar-My-Neighbour"
source_url = "https://www.richardpmann.com/beggar-my-neighbour-records.html"
