title = "Queen Attack"
blurb = "Given the position of two queens on a chess board, indicate whether or not they are positioned so that they can attack each other."
source = "J Dalbey's Programming Practice problems"
source_url = "https://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html"
