title = "Hexadecimal"
blurb = "Convert a hexadecimal number, represented as a string (e.g. \"10af8c\"), to its decimal equivalent using first principles (i.e. no, you may not use built-in or external libraries to accomplish the conversion)."
source = "All of Computer Science"
source_url = "https://www.wolframalpha.com/examples/mathematics/numbers/base-conversions"
