title = "Atbash Cipher"
blurb = "Create an implementation of the Atbash cipher, an ancient encryption system created in the Middle East."
source = "Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Atbash"
