title = "Octal"
blurb = "Convert a octal number, represented as a string (e.g. '1735263'), to its decimal equivalent using first principles (i.e. no, you may not use built-in or external libraries to accomplish the conversion)."
source = "All of Computer Science"
source_url = "https://www.wolframalpha.com/examples/mathematics/numbers/base-conversions"
