title = "Crypto Square"
blurb = "Implement the classic method for composing secret messages called a square code."
source = "J Dalbey's Programming Practice problems"
source_url = "https://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html"
