title = "ETL"
blurb = "We are going to do the `Transform` step of an Extract-Transform-Load."
source = "Exercise by the JumpstartLab team for students at The Turing School of Software and Design."
source_url = "https://turing.edu"
