title = "Allergies"
blurb = "Given a person's allergy score, determine whether or not they're allergic to a given item, and their full list of allergies."
source = "Exercise by the JumpstartLab team for students at The Turing School of Software and Design."
source_url = "https://turing.edu"
