title = "Pythagorean Triplet"
blurb = "Given an integer N, find all Pythagorean triplets for which a + b + c = N."
source = "A variation of Problem 9 from Project Euler"
source_url = "https://projecteuler.net/problem=9"
