title = "Mazy Mice"
blurb = "Meet Mickey and Minerva, two clever mice who love to navigate their way through a maze to find cheese. They enjoy a good challenge, but with only their tiny mouse brains, they prefer if there is only one correct path to the cheese."
source = "Inspired by the 'Maze Generator' created by Jan Boström at Alance AB."
source_url = "https://mazegenerator.net/"
